version: '3.8'

services:
  marketplace-ms-orders:
    build: .
    ports:
      - "8001:8000"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - DB_HOST=orders-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=marketplace-ms-orders
      - PRODUCT_MS_URL=http://marketplace-ms-products:8000
    depends_on:
      - orders-db

  orders-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: marketplace-ms-orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - orders_postgres_data:/var/lib/postgresql/data

volumes:
  orders_postgres_data: