version: '3.8'

services:
  marketplace-ms-tenant:
    build: .
    ports:
      - "8003:8000"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - DB_HOST=tenant-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=marketplace-ms-tenant
    depends_on:
      - tenant-db

  tenant-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: marketplace-ms-tenant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - tenant_postgres_data:/var/lib/postgresql/data

volumes:
  tenant_postgres_data: